"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-10-07 10:07:19.158995
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import raf.core.storage.types

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyses",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("input", sa.Text(), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=True),
        sa.Column("detected_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "steps", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "stats", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "suggestions", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyses")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("actor", sa.String(length=256), nullable=False),
        sa.Column("interface", sa.String(length=16), nullable=False),
        sa.Column("command", sa.Text(), nullable=False),
        sa.Column("workspace", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=128), nullable=False),
        sa.Column(
            "affected", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column(
            "details", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("entry_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_log_operation", ["operation"], unique=False)
        batch_op.create_index("ix_audit_log_ts", ["ts"], unique=False)

    op.create_table(
        "blobs",
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("hash", name=op.f("pk_blobs")),
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("incident_id", sa.String(length=512), nullable=True),
        sa.Column("created_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
        sa.UniqueConstraint("name", name=op.f("uq_cases_name")),
    )
    op.create_table(
        "counters",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_counters")),
    )
    op.create_table(
        "custody_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("ts", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=256), nullable=False),
        sa.Column(
            "details", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("entry_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custody_events")),
    )
    with op.batch_alter_table("custody_events", schema=None) as batch_op:
        batch_op.create_index("ix_custody_events_case", ["case_id"], unique=False)
        batch_op.create_index("ix_custody_events_evidence", ["evidence_id"], unique=False)

    op.create_table(
        "event_objects",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=512), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("ts", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("event_id", "object_id", "role", name=op.f("pk_event_objects")),
    )
    with op.batch_alter_table("event_objects", schema=None) as batch_op:
        batch_op.create_index("ix_event_objects_object_ts", ["object_id", "ts"], unique=False)

    op.create_table(
        "events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("ts", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("actor_id", sa.String(length=512), nullable=True),
        sa.Column("target_id", sa.String(length=512), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=512), nullable=False),
        sa.Column("parser", sa.String(length=128), nullable=False),
        sa.Column("record", sa.String(length=128), nullable=True),
        sa.Column("raw_ref", sa.String(length=512), nullable=True),
        sa.Column("raw", sa.Text(), nullable=True),
        sa.Column(
            "attributes", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "rel_ids", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index("ix_events_actor_ts", ["actor_id", "ts"], unique=False)
        batch_op.create_index("ix_events_category_ts", ["category", "ts"], unique=False)
        batch_op.create_index("ix_events_job_id", ["job_id"], unique=False)
        batch_op.create_index("ix_events_target_ts", ["target_id", "ts"], unique=False)
        batch_op.create_index("ix_events_ts_id", ["ts", "id"], unique=False)
        batch_op.create_index("ix_events_type_ts", ["event_type", "ts"], unique=False)

    op.create_table(
        "evidence_items",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("original_name", sa.String(length=1024), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("stored_path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("derived_from", sa.String(length=128), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column(
            "metadata", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("imported_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("ingest_job_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_items")),
    )
    with op.batch_alter_table("evidence_items", schema=None) as batch_op:
        batch_op.create_index("ix_evidence_items_case", ["case_id"], unique=False)
        batch_op.create_index("ix_evidence_items_sha256", ["sha256"], unique=False)

    op.create_table(
        "finding_objects",
        sa.Column("finding_id", sa.String(length=256), nullable=False),
        sa.Column("object_id", sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint("finding_id", "object_id", name=op.f("pk_finding_objects")),
    )
    with op.batch_alter_table("finding_objects", schema=None) as batch_op:
        batch_op.create_index("ix_finding_objects_object_id", ["object_id"], unique=False)

    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("product", sa.String(length=64), nullable=False),
        sa.Column("rule_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("severity_rank", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column(
            "affected", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "evidence", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "explanation", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "tags", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "metadata", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.create_index("ix_findings_product", ["product"], unique=False)
        batch_op.create_index("ix_findings_severity", ["severity_rank"], unique=False)
        batch_op.create_index("ix_findings_status", ["status"], unique=False)

    op.create_table(
        "ghost_models",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("base_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("parent", sa.String(length=160), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ghost_models")),
        sa.UniqueConstraint("name", name=op.f("uq_ghost_models_name")),
    )
    op.create_table(
        "ghost_ops",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_id", sa.String(length=160), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("op", sa.String(length=64), nullable=False),
        sa.Column(
            "params", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "summary", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ghost_ops")),
        sa.UniqueConstraint("model_id", "seq", name=op.f("uq_ghost_ops_model_id_seq")),
    )
    op.create_table(
        "incident_events",
        sa.Column("incident_id", sa.String(length=512), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("ts", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("incident_id", "event_id", name=op.f("pk_incident_events")),
    )
    with op.batch_alter_table("incident_events", schema=None) as batch_op:
        batch_op.create_index("ix_incident_events_event_id", ["event_id"], unique=False)
        batch_op.create_index("ix_incident_events_incident_ts", ["incident_id", "ts"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "params", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "result", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column(
            "error", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("actor", sa.String(length=256), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("started_at", raf.core.storage.types.UTCDateTime(), nullable=True),
        sa.Column("finished_at", raf.core.storage.types.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_jobs_status", ["status"], unique=False)

    op.create_table(
        "kv",
        sa.Column("namespace", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column(
            "value", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("updated_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("namespace", "key", name=op.f("pk_kv")),
    )
    op.create_table(
        "labs",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("template", sa.String(length=64), nullable=False),
        sa.Column("backend", sa.String(length=32), nullable=False),
        sa.Column(
            "config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("container_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_labs")),
    )
    op.create_table(
        "object_aliases",
        sa.Column("alias_lc", sa.String(length=1024), nullable=False),
        sa.Column("object_id", sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint("alias_lc", "object_id", name=op.f("pk_object_aliases")),
    )
    with op.batch_alter_table("object_aliases", schema=None) as batch_op:
        batch_op.create_index("ix_object_aliases_object_id", ["object_id"], unique=False)

    op.create_table(
        "objects",
        sa.Column("id", sa.String(length=512), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("name_lc", sa.String(length=1024), nullable=False),
        sa.Column("created_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("first_seen", raf.core.storage.types.UTCDateTime(), nullable=True),
        sa.Column("last_seen", raf.core.storage.types.UTCDateTime(), nullable=True),
        sa.Column("valid_from", raf.core.storage.types.UTCDateTime(), nullable=True),
        sa.Column("valid_to", raf.core.storage.types.UTCDateTime(), nullable=True),
        sa.Column("source", sa.String(length=512), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "tags", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "metadata", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("observations", sa.Integer(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_objects")),
    )
    with op.batch_alter_table("objects", schema=None) as batch_op:
        batch_op.create_index("ix_objects_name_lc", ["name_lc"], unique=False)
        batch_op.create_index("ix_objects_type_name_lc", ["type", "name_lc"], unique=False)

    op.create_table(
        "provenance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subject_id", sa.String(length=512), nullable=False),
        sa.Column("subject_kind", sa.String(length=16), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=512), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("record", sa.String(length=128), nullable=True),
        sa.Column("parser", sa.String(length=128), nullable=True),
        sa.Column("observed_at", raf.core.storage.types.UTCDateTime(), nullable=True),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("evidence_id", sa.String(length=128), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("recorded_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provenance")),
    )
    with op.batch_alter_table("provenance", schema=None) as batch_op:
        batch_op.create_index("ix_provenance_job", ["job_id"], unique=False)
        batch_op.create_index("ix_provenance_subject", ["subject_id"], unique=False)

    op.create_table(
        "ranges",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("preset", sa.String(length=64), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column(
            "config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("sim_clock", raf.core.storage.types.UTCDateTime(), nullable=True),
        sa.Column("worker_pid", sa.Integer(), nullable=True),
        sa.Column(
            "stats", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_ranges")),
    )
    op.create_table(
        "relationships",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=512), nullable=False),
        sa.Column("target_id", sa.String(length=512), nullable=False),
        sa.Column("created_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column("first_seen", raf.core.storage.types.UTCDateTime(), nullable=True),
        sa.Column("last_seen", raf.core.storage.types.UTCDateTime(), nullable=True),
        sa.Column("valid_from", raf.core.storage.types.UTCDateTime(), nullable=True),
        sa.Column("valid_to", raf.core.storage.types.UTCDateTime(), nullable=True),
        sa.Column("source", sa.String(length=512), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "metadata", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("observations", sa.Integer(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationships")),
    )
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.create_index("ix_relationships_source_type", ["source_id", "type"], unique=False)
        batch_op.create_index("ix_relationships_target_type", ["target_id", "type"], unique=False)
        batch_op.create_index("ix_relationships_type", ["type"], unique=False)

    op.create_table(
        "snapshot_items",
        sa.Column("snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("item_id", sa.String(length=512), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("snapshot_id", "kind", "item_id", name=op.f("pk_snapshot_items")),
    )
    op.create_table(
        "snapshots",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", raf.core.storage.types.UTCDateTime(), nullable=False),
        sa.Column(
            "stats", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_snapshots")),
        sa.UniqueConstraint("name", name=op.f("uq_snapshots_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snapshots")
    op.drop_table("snapshot_items")
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.drop_index("ix_relationships_type")
        batch_op.drop_index("ix_relationships_target_type")
        batch_op.drop_index("ix_relationships_source_type")

    op.drop_table("relationships")
    op.drop_table("ranges")
    with op.batch_alter_table("provenance", schema=None) as batch_op:
        batch_op.drop_index("ix_provenance_subject")
        batch_op.drop_index("ix_provenance_job")

    op.drop_table("provenance")
    with op.batch_alter_table("objects", schema=None) as batch_op:
        batch_op.drop_index("ix_objects_type_name_lc")
        batch_op.drop_index("ix_objects_name_lc")

    op.drop_table("objects")
    with op.batch_alter_table("object_aliases", schema=None) as batch_op:
        batch_op.drop_index("ix_object_aliases_object_id")

    op.drop_table("object_aliases")
    op.drop_table("labs")
    op.drop_table("kv")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_status")
        batch_op.drop_index("ix_jobs_created_at")

    op.drop_table("jobs")
    with op.batch_alter_table("incident_events", schema=None) as batch_op:
        batch_op.drop_index("ix_incident_events_incident_ts")
        batch_op.drop_index("ix_incident_events_event_id")

    op.drop_table("incident_events")
    op.drop_table("ghost_ops")
    op.drop_table("ghost_models")
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_index("ix_findings_status")
        batch_op.drop_index("ix_findings_severity")
        batch_op.drop_index("ix_findings_product")

    op.drop_table("findings")
    with op.batch_alter_table("finding_objects", schema=None) as batch_op:
        batch_op.drop_index("ix_finding_objects_object_id")

    op.drop_table("finding_objects")
    with op.batch_alter_table("evidence_items", schema=None) as batch_op:
        batch_op.drop_index("ix_evidence_items_sha256")
        batch_op.drop_index("ix_evidence_items_case")

    op.drop_table("evidence_items")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("ix_events_type_ts")
        batch_op.drop_index("ix_events_ts_id")
        batch_op.drop_index("ix_events_target_ts")
        batch_op.drop_index("ix_events_job_id")
        batch_op.drop_index("ix_events_category_ts")
        batch_op.drop_index("ix_events_actor_ts")

    op.drop_table("events")
    with op.batch_alter_table("event_objects", schema=None) as batch_op:
        batch_op.drop_index("ix_event_objects_object_ts")

    op.drop_table("event_objects")
    with op.batch_alter_table("custody_events", schema=None) as batch_op:
        batch_op.drop_index("ix_custody_events_evidence")
        batch_op.drop_index("ix_custody_events_case")

    op.drop_table("custody_events")
    op.drop_table("counters")
    op.drop_table("cases")
    op.drop_table("blobs")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_log_ts")
        batch_op.drop_index("ix_audit_log_operation")

    op.drop_table("audit_log")
    op.drop_table("analyses")
    # ### end Alembic commands ###
