import type { RafEvent } from '../../api/types';
import { ConfidenceBadge, SeverityBadge } from '../../components/Badge';
import { KeyValueList, MetadataList, Mono, Time } from '../../components/Data';
import { Icon } from '../../components/Icon';
import { ObjectChip } from '../../components/ObjectChip';

/** Raw source records are attacker-controllable input: shown verbatim as text, clearly labeled. */
export function RawRecord({ raw, reference }: { raw: string; reference?: string | null }) {
  return (
    <figure className="raw">
      <figcaption className="raw__caption">
        <Icon name="warning" size={14} />
        <span>
          Raw record — untrusted input, displayed as text
          {reference ? (
            <>
              {' '}
              · <span className="mono">{reference}</span>
            </>
          ) : null}
        </span>
      </figcaption>
      <pre className="raw__body">{raw}</pre>
    </figure>
  );
}

function Ref({ id, names }: { id: string | null; names?: Record<string, string> }) {
  if (!id) return <span className="muted">—</span>;
  return <ObjectChip id={id} name={names?.[id]} />;
}

export function EventDetail({ event, names }: { event: RafEvent; names?: Record<string, string> }) {
  return (
    <div className="stack">
      <div className="row row--wrap">
        <SeverityBadge severity={event.severity} showLabel />
        <ConfidenceBadge confidence={event.confidence} showLabel />
        {event.synthetic ? (
          <span className="tag" title="Generated by the synthetic demo or a range">
            synthetic
          </span>
        ) : null}
      </div>
      {event.message ? <p className="break">{event.message}</p> : null}
      <KeyValueList
        entries={[
          ['Time', <Time value={event.timestamp} />],
          ['Type', <Mono>{event.event_type}</Mono>],
          ['Category', `${event.category} / ${event.action}${event.outcome ? ` (${event.outcome})` : ''}`],
          ['Actor', <Ref id={event.actor} names={names} />],
          ['Target', <Ref id={event.target} names={names} />],
          ['Event ID', <Mono>{event.id}</Mono>],
        ]}
      />
      {event.objects.length > 0 ? (
        <section className="stack stack--tight">
          <h4>Involved objects</h4>
          <ul className="ref-list">
            {event.objects.map((ref) => (
              <li key={`${ref.role}:${ref.object_id}`} className="row">
                <span className="ref-list__role mono small muted">{ref.role}</span>
                <ObjectChip id={ref.object_id} name={names?.[ref.object_id]} />
              </li>
            ))}
          </ul>
        </section>
      ) : null}
      {event.incidents.length > 0 ? (
        <section className="stack stack--tight">
          <h4>Incidents</h4>
          <div className="row row--wrap">
            {event.incidents.map((id) => (
              <ObjectChip key={id} id={id} />
            ))}
          </div>
        </section>
      ) : null}
      <section className="stack stack--tight">
        <h4>Provenance</h4>
        <KeyValueList
          entries={[
            ['Source', <Mono>{event.source}</Mono>],
            ['Parser', <Mono>{event.parser}</Mono>],
            ['Record', event.record ? <Mono>{event.record}</Mono> : '—'],
            ['Job', event.job_id ? <Mono>{event.job_id}</Mono> : '—'],
            ['Ingested', <Time value={event.ingested_at ?? null} />],
          ]}
        />
      </section>
      <section className="stack stack--tight">
        <h4>Attributes</h4>
        <MetadataList metadata={event.attributes} empty="No attributes." />
      </section>
      {event.raw ? <RawRecord raw={event.raw} reference={event.raw_reference} /> : null}
    </div>
  );
}
