"""The builtin Oracle reasoner: deterministic answers composed from retrieved R$F facts.

No model is involved. Every sentence is generated by R$F from structured data and carries the IDs
it is based on, so the same workspace and question always give the same answer, and the answer is
useful with all AI features disabled.
"""

from __future__ import annotations

import shlex
from collections.abc import Callable
from contextvars import ContextVar

from raf.core.timeutil import format_ts
from raf.products.oracle.retrieval import FoundPath, Retrieval

Namer = Callable[[str], str]

#: IDs the answer being composed may cite: exactly the references of the retrieved facts.
_ALLOWED: ContextVar[frozenset[str]] = ContextVar("oracle_allowed_refs", default=frozenset())


def _cite(*ids: str | None) -> str:
    allowed = _ALLOWED.get()
    unique = [i for i in dict.fromkeys(ids) if i and i in allowed]
    return " ".join(f"[{i}]" for i in unique)


def _steps(path: FoundPath) -> list[str]:
    lines = []
    for n, hop in enumerate(path.hops, 1):
        cite = _cite(hop.relationship_id, hop.target)
        seen = f"\n     observed: {hop.observed} {_cite(hop.observed_event)}" if hop.observed else ""
        lines.append(f"  {n}. {hop.why[:1].upper()}{hop.why[1:]} {cite}{seen}")
    return lines


def _path_line(path: FoundPath, namer: Namer) -> str:
    chain = " → ".join([namer(path.subject)] + [h.target_name for h in path.hops if h.target != h.source])
    crit = f" ({path.criticality} criticality)" if path.criticality else ""
    via = f", using vulnerability {path.via_vulnerability.split(':', 1)[-1]}" if path.via_vulnerability else ""
    return (
        f"{namer(path.subject)} can obtain control of {path.target_name}{crit} in {len(path.hops)} step(s){via}, "
        f"path confidence {path.confidence:.2f}: {chain} {_cite(path.subject, path.target)}"
    )


def _findings(r: Retrieval, limit: int = 5) -> list[str]:
    if not r.findings:
        return []
    lines = ["", "Related findings"]
    for finding in r.findings[:limit]:
        lines.append(f"  {finding.severity.value:<8} {finding.title} {_cite(finding.id)}")
    return lines


def _events(r: Retrieval, namer: Namer, title: str, limit: int = 8) -> list[str]:
    if not r.events:
        return []
    lines = ["", title]
    for event in r.events[:limit]:
        actor = namer(event.actor) if event.actor else "-"
        target = f" → {namer(event.target)}" if event.target else ""
        outcome = f" ({event.outcome})" if event.outcome else ""
        lines.append(f"  {format_ts(event.timestamp)}  {event.event_type}  {actor}{target}{outcome} {_cite(event.id)}")
    return lines


def _caution(r: Retrieval) -> list[str]:
    if not r.warnings:
        return []
    lines = ["", "Untrusted data"]
    lines += [f"  {w}" for w in dict.fromkeys(r.warnings)]
    return lines


def _fact_text(r: Retrieval, prefix: str) -> list[tuple[str, list[str]]]:
    return [(f.text, f.refs) for f in r.facts if f.key.startswith(prefix)]


def compose(r: Retrieval, namer: Namer) -> str:
    handler = {
        "incident-path": _incident_path,
        "incident": _incident,
        "path": _path,
        "risk": _risk,
        "controllers": _controllers,
        "summary": _summary,
        "overview": _overview,
    }[r.intent]
    token = _ALLOWED.set(frozenset(r.refs()))
    try:
        lines = handler(r, namer)
    finally:
        _ALLOWED.reset(token)
    lines += _caution(r)
    return "\n".join(line.rstrip() for line in lines).strip()


def _incident_header(r: Retrieval, namer: Namer) -> list[str]:
    inc = r.incident or {}
    window = ""
    if inc.get("start") and inc.get("end"):
        window = f"{format_ts(inc['start'])} → {format_ts(inc['end'])}, "
    lines = [
        f"{inc.get('name')}: {inc.get('title')} {_cite(inc.get('id'))}",
        f"{window}{inc.get('events', 0)} linked event(s).",
    ]
    actors = r.summary.get("actors") or []
    if actors:
        lines.append(
            "Most active identities: "
            + ", ".join(f"{namer(a)} ({n} events)" for a, n in actors[:4])
            + " "
            + _cite(*[a for a, _ in actors[:4]])
        )
    return lines


def _incident_path(r: Retrieval, namer: Namer) -> list[str]:
    lines = _incident_header(r, namer)
    if not r.paths:
        lines += [
            "",
            "No control path from the incident's identities to a high or critical asset was found "
            "in the current graph.",
        ]
        lines += _events(r, namer, "Most significant incident events")
        lines += _findings(r)
        return lines
    path = r.paths[0]
    subject = next((e for e in r.entities if e.id == path.subject), None)
    lines += ["", "Most important security path", "  " + _path_line(path, namer)]
    if path.observed_steps:
        lines.append(
            f"  {path.observed_steps} of {len(path.hops)} step(s) appear in the incident's events, which is why "
            "this path ranks first among the identities' paths to high and critical assets."
        )
    lines += _steps(path)
    if r.blast:
        lines.append(
            f"  From {namer(path.subject)}, {r.blast['controllable_assets']} asset(s) are controllable, "
            f"{r.blast['critical_assets']} of them high or critical {_cite(path.subject)}."
        )
    for text, refs in _fact_text(r, "pivot:"):
        lines.append(f"  {text} {_cite(*refs[:8])}")
    disabled = [f for f in r.facts if f.key == f"object:{path.subject}" and "disabled" in f.text]
    if disabled or (subject is not None and subject.metadata.get("disabled")):
        lines.append(
            f"  {namer(path.subject)} is disabled now; the path shows what the account could reach, and "
            f"steps that use other credentials remain usable {_cite(path.subject)}."
        )
    lines += _events(r, namer, "Incident events on this path", limit=12)
    lines += _findings(r)
    return lines


def _incident(r: Retrieval, namer: Namer) -> list[str]:
    lines = _incident_header(r, namer)
    lines += _events(r, namer, "Most significant events", limit=12)
    lines += _findings(r)
    return lines


def _path(r: Retrieval, namer: Namer) -> list[str]:
    source, target = r.entities[0], r.entities[1]
    if not r.paths:
        lines = [
            f"No control path from {source.name} to {target.name} was found within 12 steps "
            f"{_cite(source.id, target.id)}.",
            "Network reachability alone is not control; R$F follows identities, credentials, group and role "
            "membership, administration and exploitable vulnerabilities.",
        ]
        lines += _findings(r)
        return lines
    path = r.paths[0]
    lines = ["Yes. " + _path_line(path, namer)]
    lines += _steps(path)
    lines += _findings(r)
    return lines


def _exposure_lines(r: Retrieval, namer: Namer) -> list[str]:
    exp = r.exposure
    if not exp:
        return []
    obj = exp["object"]
    lines = [
        f"{obj['name']} has {exp['level']} exposure ({exp['score']}/100, {exp['methodology']}) {_cite(obj['id'])}."
    ]
    raising = [f for f in exp["factors"] if f["sign"] == "+"]
    lowering = [f for f in exp["factors"] if f["sign"] == "-"]
    if raising:
        lines.append("Raising the score:")
        lines += [f"  +{f['points']:<3} {f['label']} {_cite(*f['evidence'][:3])}" for f in raising[:6]]
    if lowering:
        lines.append("Lowering the score:")
        lines += [f"  -{f['points']:<3} {f['label']} {_cite(*f['evidence'][:3])}" for f in lowering[:4]]
    controllers = exp.get("controllers") or []
    if controllers:
        privileged = sum(1 for c in controllers if c.get("privileged"))
        lines.append(
            f"{len(controllers)} principal(s) can obtain control of {obj['name']} ({privileged} privileged): "
            + ", ".join(c["name"] for c in controllers[:8])
            + " "
            + _cite(*[c["id"] for c in controllers[:8]])
        )
    return lines


def _risk(r: Retrieval, namer: Namer) -> list[str]:
    obj = r.entities[0]
    lines = _exposure_lines(r, namer)
    if r.exposure and "safe" in r.question.lower():
        level = r.exposure["level"]
        lead = (
            "No, not by R$F's measures. "
            if level in ("HIGH", "CRITICAL")
            else "R$F finds no high exposure; that is not proof of safety. "
        )
        lines[0] = lead + lines[0]
    crit = obj.metadata.get("criticality")
    if crit and r.exposure:
        lines.insert(
            1,
            f"Business criticality is {crit}; exposure measures how reachable, controllable and consequential it is "
            f"for an attacker {_cite(obj.id)}.",
        )
    if r.blast is not None:
        if lines:
            lines.append("")
        lines.append(
            f"If {obj.name} were compromised, {r.blast['controllable_assets']} asset(s) would be "
            f"controllable, {r.blast['critical_assets']} of them high or critical {_cite(obj.id)}."
        )
        for n, path in enumerate(r.paths[:2]):
            lines.append("  " + _path_line(path, namer))
            if n == 0:
                lines += _steps(path)
    if not lines:
        lines = [f"{obj.name} ({obj.type}) has no exposure or blast-radius model in R$F {_cite(obj.id)}."]
    lines += _events(r, namer, "Recent activity", limit=8)
    lines += _findings(r)
    return lines


def _controllers(r: Retrieval, namer: Namer) -> list[str]:
    obj = r.entities[0]
    lines = _exposure_lines(r, namer)
    if not lines:
        lines = [
            f"R$F computes who can control assets (hosts, services, networks, cloud resources); "
            f"{obj.name} is a {obj.type} {_cite(obj.id)}."
        ]
    lines += _findings(r)
    return lines


def _summary(r: Retrieval, namer: Namer) -> list[str]:
    obj = r.entities[0]
    lines = [text + " " + _cite(*refs[:1]) for text, refs in _fact_text(r, f"object:{obj.id}")]
    rels = [(text, refs) for text, refs in _fact_text(r, "rel:")]
    if rels:
        lines.append("")
        lines.append("Relationships")
        lines += [f"  {text} {_cite(refs[0])}" for text, refs in rels[:12]]
    lines += _events(r, namer, "Recent activity", limit=6)
    lines += _findings(r)
    return lines


def _overview(r: Retrieval, namer: Namer) -> list[str]:
    counts = r.summary.get("findings_by_severity") or {}
    total = sum(counts.values())
    lines = [
        f"The workspace has {total} open finding(s): "
        + ", ".join(f"{n} {sev.lower()}" for sev, n in counts.items() if n)
        + "."
        if total
        else "The workspace has no open findings."
    ]
    incidents = _fact_text(r, "incident:")
    if incidents:
        lines.append("")
        lines.append("Incidents")
        lines += [f"  {text} {_cite(*refs)}" for text, refs in incidents]
    lines += _findings(r, limit=8)
    lines += [
        "",
        "Ask about a subject for a specific answer, for example: why is DEV-01 critical, "
        "can alice reach production, or explain INC-001.",
    ]
    return lines


def suggestions(r: Retrieval, namer: Namer) -> list[str]:
    """Next R$F commands for the analyst (never executed by Oracle)."""

    def q(ref: str) -> str:
        name = namer(ref)
        # IDs can hold shell syntax (process:dev-01|20903) or spaces: quoted, a suggestion stays one command.
        return name if name.replace("-", "").replace("_", "").replace(".", "").isalnum() else shlex.quote(ref)

    out: list[str] = []
    if r.incident:
        incident = shlex.quote(str(r.incident["name"]))
        out += [f"raf timeline {incident}", f"raf lens {incident} --group-by actor"]
    for path in r.paths[:1]:
        out += [f"raf blast {q(path.subject)}", f"raf graph path {q(path.subject)} {q(path.target)}"]
        credential = next(
            (h for h in path.hops if h.relationship_type in ("CONTAINS_SECRET", "USES", "AUTHENTICATES_AS")), None
        )
        if (
            credential is not None
            and credential.relationship_id
            and not credential.relationship_id.startswith("vulnerability:")
        ):
            out += [
                "raf ghost create what-if",
                f"raf ghost modify what-if --remove-relationship {credential.relationship_id}",
                "raf ghost compare current what-if",
            ]
    if r.exposure:
        out.append(f"raf exposure show {q(r.exposure['object']['id'])}")
    if r.intent in ("summary", "risk", "controllers") and r.entities:
        out += [f"raf graph {q(r.entities[0].id)}", f"raf timeline {q(r.entities[0].id)}"]
    if r.findings:
        out.append(f"raf finding show {r.findings[0].id}")
    if r.intent == "overview":
        out += ["raf findings --severity high", "raf exposure"]
    return list(dict.fromkeys(out))[:8]
