"""R$F Oracle: answers about the workspace, grounded in retrieved R$F data.

Guarantees (independent of the provider):

* Answers are built only from facts retrieved from the workspace; each fact names the IDs that
  support it and the module that produced it.
* Imported text is untrusted data. It is kept apart from R$F's own wording, passed to a model only
  inside nonce-delimited data markers, and flagged when it resembles instructions.
* Every ID a model cites is validated against the retrieved data; anything else is reported in
  ``invalid_references`` and marked in the answer. The builtin reasoner can only cite retrieved IDs.
* Oracle has no tools and changes nothing. Answers are never stored as security data (objects,
  relationships, findings); only an audit record of the question is kept.
"""

from __future__ import annotations

import hashlib
import re
from datetime import datetime
from typing import Any

from pydantic import Field

from raf.core.context.app import RafContext
from raf.core.errors import DependencyUnavailableError, InvalidInputError
from raf.core.objects.models import RafModel
from raf.core.timeutil import format_ts, utcnow
from raf.products.oracle.prompt import build_prompt, cited_ids
from raf.products.oracle.providers import (
    ModelProvider,
    OpenAICompatibleProvider,
    ProviderError,
    is_loopback,
    transport_warning,
    validate_base_url,
)
from raf.products.oracle.reasoner import compose, suggestions
from raf.products.oracle.retrieval import Fact, Retrieval, Retriever

MAX_QUESTION = 2000
NOTICE = (
    "Generated by R$F Oracle from workspace data. It is an explanation, not authoritative security data: "
    "verify it against the cited objects."
)
_CONTROL_RE = re.compile(r"[\x00-\x08\x0b-\x1f\x7f-\x9f]")


class Citation(RafModel):
    id: str
    label: str
    type: str


class OracleAnswer(RafModel):
    question: str
    answer: str
    provider: str
    mode: str  # builtin | model | builtin-fallback
    model: str | None = None
    intent: str
    entities: list[dict[str, str]] = Field(default_factory=list)
    citations: list[Citation] = Field(default_factory=list)
    invalid_references: list[str] = Field(default_factory=list)
    facts: list[Fact] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    generated_at: datetime
    notice: str = NOTICE


def clean_question(question: str) -> str:
    text = _CONTROL_RE.sub(" ", question or "").strip()
    if not text:
        raise InvalidInputError("Ask a question.", hint='raf oracle ask "Explain the most important path in INC-001"')
    if len(text) > MAX_QUESTION:
        raise InvalidInputError(f"The question is longer than {MAX_QUESTION} characters.")
    return text


class OracleService:
    def __init__(self, ctx: RafContext, provider: ModelProvider | None = None) -> None:
        self.ctx = ctx
        self._injected = provider

    # ------------------------------------------------------------------ configuration
    def provider_name(self) -> str:
        if self._injected is not None:
            return self._injected.name
        return str(self.ctx.settings.get("oracle.provider"))

    def model_provider(self) -> ModelProvider:
        if self._injected is not None:
            return self._injected
        settings = self.ctx.settings
        return OpenAICompatibleProvider(
            str(settings.get("oracle.base_url")),
            str(settings.get("oracle.model") or ""),
            api_key=settings.secret("oracle.api_key"),
            timeout=float(settings.get("oracle.timeout_seconds")),
        )

    def status(self) -> dict[str, Any]:
        """Provider configuration and readiness. Never includes the API key (only whether one is set)."""
        settings = self.ctx.settings
        name = self.provider_name()
        data: dict[str, Any] = {
            "provider": name,
            "enabled": name != "disabled",
            "max_facts": int(settings.get("oracle.max_facts")),
            "tools": "none (Oracle reads R$F data and changes nothing)",
            "stores_answers": False,
        }
        if name == "builtin":
            data.update(ready=True, mode="builtin", detail="deterministic reasoner over R$F data; no model, no network")
        elif name == "disabled":
            data.update(ready=False, mode="disabled", detail="Oracle is disabled; every other R$F feature works")
        else:
            base_url = str(settings.get("oracle.base_url"))
            model = str(settings.get("oracle.model") or "")
            data.update(
                mode="model",
                base_url=base_url,
                model=model or None,
                loopback=is_loopback(base_url),
                api_key_configured=bool(settings.secret("oracle.api_key")),
                timeout_seconds=float(settings.get("oracle.timeout_seconds")),
            )
            problems = []
            try:
                validate_base_url(base_url)
            except Exception as exc:  # noqa: BLE001 - reported, not raised
                problems.append(str(getattr(exc, "message", exc)))
            if not model:
                problems.append("oracle.model is not set")
            warning = transport_warning(base_url)
            if warning:
                data["warning"] = warning
            if not is_loopback(base_url):
                data["data_leaves_host"] = True
            data.update(
                ready=not problems,
                detail="; ".join(problems)
                or "retrieved facts are sent to the configured server; answers are validated against them",
            )
        return data

    # ------------------------------------------------------------------ answering
    def _label(self, ref: str, retrieval: Retrieval, retriever: Retriever) -> Citation:
        kind = ref.split(":", 1)[0]
        for event in retrieval.events:
            if event.id == ref:
                return Citation(id=ref, type="event", label=f"{event.event_type} at {format_ts(event.timestamp)}")
        for finding in retrieval.findings:
            if finding.id == ref:
                return Citation(id=ref, type="finding", label=finding.title)
        if kind == "rel":
            rel = retriever.graph().all_edges.get(ref)
            if rel is not None:
                return Citation(
                    id=ref,
                    type="relationship",
                    label=f"{retriever.name(rel.source_object)} "
                    f"{rel.relationship_type} {retriever.name(rel.target_object)}",
                )
        node = retriever.graph().all_nodes.get(ref)
        return Citation(id=ref, type=node.type if node else kind, label=node.name if node else ref.split(":", 1)[-1])

    def ask(self, question: str) -> OracleAnswer:
        text = clean_question(question)
        name = self.provider_name()
        if name == "disabled":
            raise DependencyUnavailableError(
                "R$F Oracle is disabled.",
                reason="oracle.provider is set to 'disabled'",
                hint="Enable the deterministic builtin reasoner: raf config set oracle.provider builtin",
            )
        retriever = Retriever(self.ctx, max_facts=int(self.ctx.settings.get("oracle.max_facts")))
        retrieval = retriever.retrieve(text)
        allowed = retrieval.refs()
        warnings = list(dict.fromkeys(retrieval.warnings))
        mode, model = "builtin", None
        if name == "builtin":
            answer = compose(retrieval, retriever.name)
        else:
            provider = self.model_provider()
            model = provider.model
            try:
                answer = provider.complete(build_prompt(retrieval))
                mode = "model"
            except ProviderError as exc:
                warnings.append(f"The model provider failed ({exc.message}); answered with the builtin reasoner.")
                answer, mode = compose(retrieval, retriever.name), "builtin-fallback"
        cited = cited_ids(answer)
        invalid = [ref for ref in cited if ref not in allowed]
        for ref in invalid:
            answer = answer.replace(f"[{ref}]", f"[{ref} - not in R$F data]")
        if invalid:
            warnings.append(
                f"The answer cited {len(invalid)} reference(s) that are not in the retrieved R$F data; "
                "they are marked and are not citations."
            )
        valid = [ref for ref in cited if ref in allowed]
        if mode == "model" and retrieval.facts and not valid:
            warnings.append("The model answer cites no R$F data; treat it as unverified.")
        result = OracleAnswer(
            question=text,
            answer=answer,
            provider=name,
            mode=mode,
            model=model,
            intent=retrieval.intent,
            entities=[{"id": e.id, "name": e.name, "type": e.type} for e in retrieval.entities],
            citations=[self._label(ref, retrieval, retriever) for ref in valid],
            invalid_references=invalid,
            facts=retrieval.facts,
            suggestions=suggestions(retrieval, retriever.name),
            warnings=warnings,
            generated_at=utcnow(),
        )
        self.ctx.audit.record(
            "oracle.ask",
            affected=[e.id for e in retrieval.entities][:10],
            details={
                "question_sha256": hashlib.sha256(text.encode()).hexdigest(),
                "question": text[:200],
                "provider": name,
                "mode": mode,
                "intent": retrieval.intent,
                "facts": len(retrieval.facts),
                "citations": len(valid),
                "invalid_references": invalid[:20],
            },
        )
        return result
